algoritmo "semnome"
// Função :
// Autor :
// Data : 18/03/2015
// Seção de Declarações 
var
num1:inteiro
num2:inteiro
inicio
escreval("digite um valor aqui:")
leia(num1)
limpatela
escreval("digite outro valor aqui:")
leia(num2)
limpatela
escreval("a soma dos valores é ="," ",num1 + num2)
escreval("a subtração dos valores é ="," ",num1 - num2)
escreval("a multiplicação dos valores é ="," ",num1 * num2)
escreval("a divisao dos valores é ="," ", num1 / num2)

fimalgoritmo
